export const GET_ERRORS = 'GET_ERRORS'
export const SET_USER = 'SET_USER'

export const GET_CUSTOMERS = 'GET_CUSTOMERS'
export const CUSTOMERS_LOADING = 'CUSTOMERS_LOADING'
export const GET_CUSTOMER_BY_ID = 'GET_CUSTOMER_BY_ID'
export const ADD_CUSTOMER = 'ADD_CUSTOMER'
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER'
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER'

export const GET_STAFF = 'GET_STAFF'
export const STAFF_LOADING = 'STAFF_LOADING'
export const GET_STAFF_BY_ID = 'GET_STAFF_BY_ID'

export const GET_COMMENTS = 'GET_COMMENTS'
export const COMMENTS_LOADING = 'COMMENTS_LOADING'

export const GET_PURCHASES = 'GET_PURCHASES'
export const PURCHASES_LOADING = 'PURCHASES_LOADING'

export const GET_SHIFTS = 'GET_SHIFTS'
export const SHIFTS_LOADING = 'SHIFTS_LOADING'

export const GET_VISITS = 'GET_VISITS'
export const VISITS_LOADING = 'VISITS_LOADING'

export const GET_HOLDS = 'GET_HOLDS'
export const HOLDS_LOADING = 'HOLDS_LOADING'