export const GET_ERRORS = 'GET_ERRORS'
export const SET_USER = 'SET_USER'

export const GET_CUSTOMERS = 'GET_CUSTOMERS'
export const CUSTOMERS_LOADING = 'CUSTOMERS_LOADING'
export const GET_CUSTOMER_BY_ID = 'GET_CUSTOMER_BY_ID'

export const GET_STAFF = 'GET_STAFF'
export const STAFF_LOADING = 'STAFF_LOADING'
export const GET_STAFF_BY_ID = 'GET_STAFF_BY_ID'

export const GET_COMMENTS = 'GET_COMMENTS'
export const COMMENTS_LOADING = 'COMMENTS_LOADING'